In [1]:
import os
from pathlib import Path

# Print the current working directory
starting_path = os.getcwd()

# Change directory to sleap-roots
if os.path.basename(os.getcwd()) == "sleap-roots":
    pass
else:
    os.chdir("..")
    
current_path = os.getcwd()

print(f"Starting directory: {starting_path}")
print(f"Changed to directory: {current_path}")

import pandas as pd
import numpy as np

import sleap_roots as sr
import sleap_io as sio

from sleap_roots.bases import *
from sleap_roots.tips import *

Starting directory: /Users/andrewoconnor/Projects/sleap-roots/notebooks
Changed to directory: /Users/andrewoconnor/Projects/sleap-roots


In [2]:
# (instances, nodes, 2
single_inst = np.array([[[0,0], [1, 1], [2,2], [3,3], [4,4]]])
single_inst.shape

base_pt_single_inst = get_bases(single_inst)
tip_pt_single_inst = get_tips(single_inst)

base_pt_x_single_inst = get_base_xs(base_pt_single_inst)
tip_pt_x_single_inst = get_tip_xs(tip_pt_single_inst)

base_pt_y_single_inst = get_base_ys(base_pt_single_inst)
tip_pt_y_single_inst = get_tip_ys(tip_pt_single_inst)

print("BASE INFO")
print(f"x: {base_pt_x_single_inst}")
print(f"y: {base_pt_y_single_inst}")

print()

print("TIP INFO")
print(f"x: {tip_pt_x_single_inst}")
print(f"y: {tip_pt_y_single_inst}")


BASE INFO
x: 0
y: 0

TIP INFO
x: 4
y: 4


In [3]:
folder_path = "tests/data/canola_7do"
all_slps = sr.find_all_slp_paths(folder_path)

series = sr.load_series_from_slps(all_slps, h5s=True)[0]

In [4]:
series

Series(series_name='919QDUH', h5_path='tests/data/canola_7do/919QDUH.h5', primary_path='tests/data/canola_7do/919QDUH.primary.predictions.slp', lateral_path='tests/data/canola_7do/919QDUH.lateral.predictions.slp', crown_path=None, primary_labels=Labels(labeled_frames=72, videos=1, skeletons=1, tracks=0, suggestions=0), lateral_labels=Labels(labeled_frames=72, videos=1, skeletons=1, tracks=0, suggestions=0), crown_labels=None, video=Video(filename="tests/data/canola_7do/919QDUH.h5", shape=(72, 1080, 2048, 1), dataset=vol, backend=HDF5Video), csv_path=None)

In [5]:
from sleap_roots.lengths import get_max_length_pts


get_max_length_pts(series.get_primary_points(67)).shape

(6, 2)

In [6]:
primary_max_length_pts = get_max_length_pts(series.get_primary_points(64))
primary_max_length_pts

array([[1093.03393555,  140.13084412],
       [1248.5793457 ,  300.26016235],
       [1316.03979492,  480.79904175],
       [1324.23205566,  652.74291992],
       [1332.38232422,  844.80493164],
       [1267.95690918, 1024.90112305]])

In [7]:
tip_pt = get_tips(primary_max_length_pts)
tip_pt

array([1267.95690918, 1024.90112305])

In [19]:
tips_no_pts = np.array(
    [
        [
            [1, 2],
            [np.nan, np.nan],
        ],
        [
            [5, 6],
            [np.nan, np.nan],
        ],
    ]
)

tips_no_pts.shape

(2, 2, 2)

In [26]:
tips = get_tips(tips_no_pts)
tips.shape

(2, 2)

In [ ]:
get_tip_xs(tips)

(2,)

In [18]:
np.float64(123.356).shape

()

In [ ]:
# single instance root
tips[[0]]

array([[nan, nan]])

In [27]:
get_tip_xs(tips[[0]])

np.float64(nan)